/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.german.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author LAB-315
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        frSoftware = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnJugador = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pPass = new javax.swing.JPasswordField();
        bttnEnviar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        btnJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rescourse/jugador.png"))); // NOI18N
        jPanel1.add(btnJugador);

        btnSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rescourse/seleccion.png"))); // NOI18N
        jPanel1.add(btnSeleccion);

        btnPartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rescourse/partido.png"))); // NOI18N
        jPanel1.add(btnPartidos);

        btnRandom.setText("random");
        jPanel1.add(btnRandom);

        javax.swing.GroupLayout frSoftwareLayout = new javax.swing.GroupLayout(frSoftware.getContentPane());
        frSoftware.getContentPane().setLayout(frSoftwareLayout);
        frSoftwareLayout.setHorizontalGroup(
            frSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, Short.MAX_VALUE)
        );
        frSoftwareLayout.setVerticalGroup(
            frSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Usuario");

        jLabel2.setText("Password");

        bttnEnviar.setBackground(new java.awt.Color(153, 255, 153));
        bttnEnviar.setForeground(new java.awt.Color(0, 153, 0));
        bttnEnviar.setText("Submit");
        bttnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(pPass)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bttnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnEnviar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEnviarActionPerformed
        abrirVentana();
    }//GEN-LAST:event_bttnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.nimbus.NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new App().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JButton bttnEnviar;
    private javax.swing.JFrame frSoftware;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void abrirVentana() {
        frSoftware.setVisible(true);
        frSoftware.setBounds(0,0,800,600);
        frSoftware.setLocationRelativeTo(null);
    }
}
